apiVersion: apps/v1
kind: Deployment  # 오타 수정
metadata:
  name: myweb-daemonset
spec:
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        image: web-cicd
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d  # 경로 수정이 필요할 수 있습니다. 기본적으로 nginx 설정은 /etc/nginx/conf.d 내에 위치합니다.
        - name: nginx-logs
          mountPath: /var/log/nginx
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
      - name: filebeat
        image: 062061726924.dkr.ecr.ap-northeast-2.amazonaws.com/filebeat:latest
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      - name: nginx-logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: myweb-svc
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: myweb
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
