apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb
spec:
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      # nodeSelector:
      #   intent: apps
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     topologyKey: capacity-spread
      #     whenUnsatisfiable: DoNotSchedule    
      #     labelSelector:
      #       matchLabels:
      #         app: inflate-weight  
      containers:
      - name: myweb
        image: web-cicd
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf
        - name: nginx-logs
          mountPath: /var/log/nginx
        resources:
          requests:
            cpu: "10m"
            memory: "20Mi"
          limits:
            cpu: "20m"
            memory: "40Mi"


---
apiVersion: v1
kind: Service
metadata:
  name: myweb-svc
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: myweb
  ports:
  - port: 80
    targetPort: 80
  type: NodePort