apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fastapi
  namespace: default # 필요에 따라 적절한 네임스페이스로 변경하세요
  annotations:
    downscaler/downtime-replicas: "1"
    downscaler/uptime: "Mon-Fri 07:30-20:30 ASia/Seoul"
    # downscaler/downtime: "Mon-Fri 21:30-23:30 ASia/Seoul"

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapi
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
