apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default-seokhyun-provisioner
spec:
  requirements:
    - key: "karpenter.k8s.aws/instance-category"
      operator: In
      values: ["t"]
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: Gt
      values: ["2"] # CPU가 2개 이상인 인스턴스
    - key: "karpenter.k8s.aws/instance-memory"
      operator: Gt
      values: ["8Gi"] # 메모리가 8GiB 이상인 인스턴스
    - key: "karpenter.k8s.aws/instance-generation"
      operator: Gt
      values: ["3"] # 세대가 3 이상인 인스턴스
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot"] # 스팟 인스턴스 사용
  provider: 
    subnetSelector:
      "karpenter.sh/discovery": "ozzorago-eks-tEFOFGqb"
    securityGroupSelector:
      "karpenter.sh/discovery": "ozzorago-eks-tEFOFGqb"
    instanceProfile: "eks-e4c6f4e9-424b-d17e-6cc7-15fb171944ad"
  ttlSecondsAfterEmpty: 300
