apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"karpenter.sh/v1alpha5","kind":"Provisioner","metadata":{"annotations":{},"name":"default-seokhyun-provisioner-ondemand"},"spec":{"requirements":null,"ttlSecondsAfterEmpty":300}}
  creationTimestamp: "2024-03-13T07:21:45Z"
  generation: 2
  name: on-demand
  resourceVersion: "15557650"
  uid: 3bf8cc98-1ffa-49af-b88c-d5216fbeb904
spec:
  labels:
    intent: apps
  weight: 100
  consolidation:
    enabled: true
  provider:
    instanceProfile: eks-e4c6f4e9-424b-d17e-6cc7-15fb171944ad
    securityGroupSelector:
      karpenter.sh/discovery: ozzorago-eks-tEFOFGqb
    subnetSelector:
      karpenter.sh/discovery: ozzorago-eks-tEFOFGqb
  requirements:
    - key: kubernetes.io/os
      operator: In
      values:
      - linux
    - key: kubernetes.io/arch
      operator: In
      values:
      - amd64
    - key: karpenter.sh/capacity-type
      operator: In
      values:
      - on-demand
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values:
      - t
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values:
      - "2"
    - key: capacity-spread
      operator: In
      values:
      - "1"  

