apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 062061726924.dkr.ecr.ap-northeast-2.amazonaws.com/filebeat:arm
        ports:
        - containerPort: 80
