apiVersion: v1
data:
  dbname: Ym9va21hcmtz
  dbhost: bXlzcWwtc3ZjLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw=
  username: YWRtaW4=
  userpass: cXdlcjEyMzQ=
kind: Secret
metadata:
  name: mysql-secret
